// <auto-generated />
namespace RC.Teste.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CriarBancoDeDados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriarBancoDeDados));
        
        string IMigrationMetadata.Id
        {
            get { return "202001122234342_CriarBancoDeDados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
